services:
  app:
    build: .
    container_name: monew-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - postgres
    env_file:
      - .env
    environment:
      # ${변수명:-기본값}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres:5432/postgres}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-monew1234}
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI:-mongodb://mongodb:27017/monew}

      # AWS/NAVER 설정
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY:-dummy}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY:-dummy}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID:-dummy}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET:-dummy}
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: monew-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: monew-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=monew1234
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

volumes:
  mongo-data:
  pg-data: