spring:
  application:
    name: MoNew
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
