spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    username: monew_user
    password: monew_pass
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/monew_db

# 로컬 테스트용 S3
cloud:
  aws:
    s3:
      bucket: monew-backup-dev
    region:
      static: ap-northeast-2
    stack:
      auto: false