spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DB_ENDPOINT}:5432/monew
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    mongodb:
      uri: mongodb://${MONGO_ENDPOINT}:27017/monew_db

# 실제 AWS S3 설정
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME} # 직접 적으시는 것보다 변수 처리가 안전합니다
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false

    log:
      s3:
        bucket: ${AWS_LOG_BUCKET_NAME}
      credentials:
        access-key: ${AWS_LOG_ACCESS_KEY}
        secret-key: ${AWS_LOG_SECRET_KEY}
      region:
        static: ${AWS_LOG_REGION}