spring:
  profiles:
    active: dev # 기본 실행 환경을 dev로 지정

  datasource:
    driver-class-name: org.postgresql.Driver # 모든 환경 공통 드라이버

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # 쿼리 확인을 위해 공통 적용 (운영 시 prod에서 끌 수 있음)
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{request_id}] [%X{client_ip}] %msg%n"

# 뉴스 소스는 모든 환경 공통이므로 여기에 둡니다.
news:
  rss:
    sources:
      - name: "한국경제"
        url: "https://www.hankyung.com/feed/all-news"
      - name: "조선일보"
        url: "https://www.chosun.com/arc/outboundfeeds/rss/category/all-posts/"
      - name: "연합뉴스"
        url: "https://www.yonhapnewstv.co.kr/browse/feed/"