spring:
  profiles:
    active: dev # 기본 실행 환경을 dev로 지정

  datasource:
    driver-class-name: org.postgresql.Driver # 모든 환경 공통 드라이버

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # 쿼리 확인을 위해 공통 적용 (운영 시 prod에서 끌 수 있음)
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{request_id}] [%X{client_ip}] %msg%n"

# 뉴스 소스는 모든 환경 공통이므로 여기에 둡니다.
news:
  rss:
    api:
      naver:
        client-id: ${NAVER_CLIENT_ID}
        client-secret: ${NAVER_CLIENT_SECRET}
        url: "https://openapi.naver.com/v1/search/news.json"
    rss:
      hankyung: ${RSS_URL_HANKYUNG:https://www.hankyung.com/feed/all-news}
      chosun: ${RSS_URL_CHOSUN:https://www.chosun.com/arc/outboundfeeds/rss/?outputType=xml}
      yonhap: ${RSS_URL_YONHAP:https://www.yna.co.kr/rss/news.xml}