name: SonarCloud Analysis

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and analyze with SonarCloud
        env:
          SPRING_BATCH_JDBC_INITIALIZER_ENABLED: "false"
          GRADLE_OPTS: "-Xmx3g -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DATABASE_TO_UPPER=FALSE;NON_KEYWORDS=COMMENT,LIKE
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: ""
          SPRING_DATASOURCE_PORT: ${{ secrets.SPRING_DATASOURCE_PORT }}
          SPRING_DATA_MONGODB_URI: mongodb://127.0.0.1:27017/test_db
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_LOG_ACCESS_KEY: ${{ secrets.AWS_LOG_ACCESS_KEY }}
          AWS_LOG_SECRET_KEY: ${{ secrets.AWS_LOG_SECRET_KEY }}
          AWS_LOG_BUCKET_NAME: ${{ secrets.AWS_LOG_BUCKET_NAME }}
          AWS_LOG_REGION: ${{ vars.AWS_LOG_REGION }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        # 1. sleep 40: 무료 티어의 느린 가상 환경에서도 MongoDB가 완전히 부팅될 시간을 확보합니다.
        # 2. clean: 이전 빌드 잔재를 지워 로컬과 동일한 깨끗한 환경을 보장합니다.
        run: |
          sleep 40
          ./gradlew clean build jacocoTestReport sonar \
            -Dspring.profiles.active=test \
            -Dspring.batch.jdbc.initialize-schema=never \
            -Dspring.batch.job.enabled=false \
            --info --stacktrace

      - name: Display Test Error Details
        if: failure()
        run: |
          echo "검색에 실패한 상세 에러 로그를 출력합니다..."
          find build/test-results/test -name "*.xml" -exec cat {} +